Read in data and convert it to ascii characters
Manan-dev/ChatRegex pull request #12
Opened 2023-09-29 19:43 UTC by Manan-dev

2023-09-29 20:14 UTC, zac-perry reviewed
Tested and looks good to me!

2023-09-29 20:25 UTC, andreicozma1 commented on lib/dataset.py
> +    return text
Good. One thought: if the original file formatting happens to be a different encoding (for whatever reason), this may end up performing 2 different conversions (1st to utf-8 and 2nd to ascii), and not sure how that'll go.

Would doing it in 1 step like this work?
```
with open(file_path, "r", encoding='ascii', errors='ignore') as f:
```

2023-09-29 20:31 UTC, andreicozma1 commented on lib/dataset.py
> +def read_data(name_of_file):
let's pass a file_path as an argument instead of a filename to make this more generic.
In the future, we can allow the user to pass a path as a command line argument; for something like that to work, this function can't assume that it'll be located in the dataset directory.

2023-09-29 20:41 UTC, andreicozma1 requested changes
just 2 minor things in comments above

2023-09-29 21:40 UTC, Manan-dev commented on lib/dataset.py
> +    return text
Sure it should work!

2023-09-29 21:40 UTC, Manan-dev commented on lib/dataset.py
> +def read_data(name_of_file):
Good idea

2023-09-30 13:15 UTC, andreicozma1 approved these changes
lgtm!

2023-09-30 13:16 UTC, merged