Split data into data structures
Manan-dev/ChatRegex pull request #21
Opened 2023-10-04 21:19 UTC by zac-perry

Multiple new functions were added for the preprocessing

- Added **detect_chapter_format**, **change_chapter_format**, **convert_chapter_to_numeric**, and **roman_to_int** functions to standardize the chapter heading format for each text. This allows for all text to be processed the same.
- **_NOTE:_** This was kinda gross to do for the murder_on_the_links text, as it used drastically different formatting. I decided to map each chapter number and title in the table of contents exactly to those in the text to prevent changing anything that was not a chapter heading.

- Added **combine_paragraphs** to combine all paragraphs for each chapter

- Added **create_chapter_map** in order to map each sentence to their respective chapter. Resulting map = key: Chapter #, val: Array of all sentences

2023-10-07 00:09 UTC, andreicozma1 requested changes
I tried running it but crashes
```
python3 main.py -i ./dataset/the_man_the_brown_suit.txt
```

2023-10-07 00:09 UTC, andreicozma1 commented on lib/dataset.py
> +    text = re.sub(r'[\'"“”‘’]', '', text)           # remove all quotes, including unicode quotes. This is needed on my machine to fully remove them.
Are the Unicode quotes still needed since we assume the text is converted to ascii at the beginning? 
The Unicode quotes would disappear anyways and the ascii quotes would be removed by the remove punctuation function.

2023-10-07 00:09 UTC, andreicozma1 commented on lib/dataset.py
> +        print("Does not support this format of chapter text")
We probably want to figure out a better way to do this rather than the whole preprocessing function returning empty string

2023-10-07 00:09 UTC, andreicozma1 commented on lib/dataset.py
> +    chapter_map = create_chapter_map(text)
Should we have the preprocessing stage deal with only the text -> text part? Thinking might be better to keep preprocessing and mapping/feature extraction stages separate

2023-10-07 00:09 UTC, andreicozma1 commented on lib/dataset.py
> +    formats = [r'^CHAPTER [IVXLCDM]+',  r'^Chapter [IVXLCDM]+',  r'^\d+']
Let's combine this into a singular regex pattern. Looks like we might be able to solely rely on the case-insensitive matching for the Chapter part. Also, the numbering part could be expressed as a union between Roman numerals and the \d+, such that it accepts either-or. Lastly, we should specify the end of line character at the end of the pattern for robustness.

2023-10-07 00:09 UTC, andreicozma1 commented on lib/dataset.py
> +    return text
Is this for fixing the random linebreaks in the middle of sentences in the original text?
Regarding the first part, `text = re.sub(r'\n\n', r'\n', text)`, this (should) already be handled of by the `remove_extra_whitespace` function.

Could you try this?
```
re.sub(r"([^\n])\n([^\n])", r"\1 \2", text)
```



the above would be more robust since it doesn't depend on the presence of "Chapter" and only relies on the existence of newlines on individual lines.

2023-10-07 00:09 UTC, andreicozma1 commented on lib/utils.py
> +    return new_chapter_heading
Is there a reason we need to convert the headings? If we just use the first line as the key in the mapping, it allows the chatbot to respond with the same chapter name format as it's stated in the text. Thinking it would be confusing for the chatbot to respond "its in chapter 0" and then the user looks at the text and there's no chapter 0 to be found.

2023-10-07 00:11 UTC, andreicozma1 commented on lib/dataset.py
> +    text = re.sub(r'[\'"“”‘’]', '', text)           # remove all quotes, including unicode quotes. This is needed on my machine to fully remove them.
When testing in the notebook, did you use the read_data function?
![image](https://github.com/Manan-dev/ChatRegex/assets/14914491/d3769e5d-59d1-4e24-a655-f8422a1e32eb)

notice the `encoding="ascii", errors="ignore"`, so when testing in notebook this might be where the discrepancy comes from. The ignore part should remove any non-ascii characters (including those quotes).

2023-10-07 00:18 UTC, andreicozma1 commented on lib/dataset.py
> +    return text
The current implementation doesn't seem to function as intended.
Example:
![image](https://github.com/Manan-dev/ChatRegex/assets/14914491/2e78817a-6088-4e3e-87d1-8f3266e4cfbd)

(note: I commented out the stopword removal so it's easier to see the issue.)

We might want to work with the stopword removal commented out and uncomment it in a later PR when everything else is set in stone.

2023-10-07 00:59 UTC, andreicozma1 commented
I'm thinking there's possibly wrong order of operations in the preprocess.py function.

I think I've found a somewhat good order that is robust to that we can build upon that. It's still got some little quirks here and there (For example, Mr., Mrs., acronyms with periods, etc, but those are minor issues). However, the rest has got pretty good consistency. All paragraphs are separated by \n\n and sentences are separated by single \n

Let's work off this order for the fixes and improvements to add to this branch:

![image](https://github.com/Manan-dev/ChatRegex/assets/14914491/c7334ac9-301a-41b5-b186-126ba5278e79)

Result:

![image](https://github.com/Manan-dev/ChatRegex/assets/14914491/56dd8ec2-74a2-49bd-87f0-bd86ad8cb563)

I removed the stopword removal in the above example to visualize it better. While we work let's keep it commented out at the end of the preprocess_data function bc it kind of gets in the way of interpreting what's going on. We'll uncomment it at a later stage.

2023-10-07 19:49 UTC, zac-perry commented on lib/dataset.py
> +    chapter_map = create_chapter_map(text)
Yeah that makes sense to me. Would you want to just do all of the mapping stuff in a separate function/functions then?

2023-10-07 19:49 UTC, zac-perry commented on lib/utils.py
> +    return new_chapter_heading
So my original idea (which involved a lot of over complicating), was to preprocess each book differently, since they all had relatively different formatting with the chapter headings. I figured standardizing it would cut down on code and allow them all to be processed the same. You are right, though. Having the key just be the actual, un-changed chapter heading would be a lot easier for the chatbot.

2023-10-07 19:50 UTC, zac-perry commented on lib/dataset.py
> +    text = re.sub(r'[\'"“”‘’]', '', text)           # remove all quotes, including unicode quotes. This is needed on my machine to fully remove them.
Ah yes, I totally overlooked this. I'll be sure to remove it!

2023-10-07 19:52 UTC, zac-perry commented on lib/dataset.py
> +    return text
Ah I see. Yeah its intention was to remove the lines between paragraphs within each chapter & combine them with a single \n. That way each chapter heading was followed by all of the paragraphs and text within it, without any double newlines separating any paragraphs.

But, you are correct that there is an issue currently with the stop word removal commented it. It appears it's just the order of operations at the moment. I will look more into this.

2023-10-07 19:54 UTC, zac-perry commented on lib/dataset.py
> +    return text
> Is this for fixing the random linebreaks in the middle of sentences in the original text? Regarding the first part, `text = re.sub(r'\n\n', r'\n', text)`, this (should) already be handled of by the `remove_extra_whitespace` function.
> 
> Could you try this?
> 
> ```
> re.sub(r"([^\n])\n([^\n])", r"\1 \2", text)
> ```
> 
> the above would be more robust since it doesn't depend on the presence of "Chapter" and only relies on the existence of newlines on individual lines.

This was originally for getting rid of the double newlines that separated the paragraphs. That way, each chapter was followed by just one cohesive things of text (all paragraphs and sentences combined, separated by a singular newline). For me, just using the remove_extra_whitespace function did not work for this purpose. This regex `re.sub(r"([^\n])\n([^\n])", r"\1 \2", text)` also doesn't seem to remove the line spacing between paragraphs either

2023-10-07 19:56 UTC, zac-perry commented
> I tried running it but crashes
> 
> ```
> python3 main.py -i ./dataset/the_man_the_brown_suit.txt
> ```

Oh yeah, I changed the name of the function to "preprocess_data" rather than "process_data". I just forgot to update other parts of the code that called it by its previous name. That's why it crashes

2023-10-07 20:00 UTC, zac-perry commented
> I'm thinking there's possibly wrong order of operations in the preprocess.py function.
> 
> I think I've found a somewhat good order that is robust to that we can build upon that. It's still got some little quirks here and there (For example, Mr., Mrs., acronyms with periods, etc, but those are minor issues). However, the rest has got pretty good consistency. All paragraphs are separated by \n\n and sentences are separated by single \n
> 
> Let's work off this order for the fixes and improvements to add to this branch:
> 
> ![image](https://private-user-images.githubusercontent.com/14914491/273353546-c7334ac9-301a-41b5-b186-126ba5278e79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTY3MDkwOTYsIm5iZiI6MTY5NjcwODc5NiwicGF0aCI6Ii8xNDkxNDQ5MS8yNzMzNTM1NDYtYzczMzRhYzktMzAxYS00MWI1LWIxODYtMTI2YmE1Mjc4ZTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMDA3VDE5NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwM2Y1NTg1OGNmOTkyZWQ3MzQ3NDZiMjYxY2NlODQ2MGNmYjRjMmQ3ZDhmYmU2NjUyZDAwMmE2NmIxNzU2NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bvb4L4RB3JuOB-VvG_-9qBPqxqPqsFxHuudsUbKNm7o)
> 
> Result:
> 
> ![image](https://private-user-images.githubusercontent.com/14914491/273353612-56dd8ec2-74a2-49bd-87f0-bd86ad8cb563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTY3MDkwOTYsIm5iZiI6MTY5NjcwODc5NiwicGF0aCI6Ii8xNDkxNDQ5MS8yNzMzNTM2MTItNTZkZDhlYzItNzRhMi00OWJkLTg3ZjAtYmQ4NmFkOGNiNTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMDA3VDE5NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZDliNDZkMTIzMTY5ZWZmYWRmMGZiMmM5YTczNmVjYzU1NmM4YmI5ZDk1MjU4NmIzN2E5NjYwYjZhNTZhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-RdXDGrOQNvkySRZViaCj-A6dBZcxn2_oXdvWSKjyh0)
> 
> I removed the stopword removal in the above example to visualize it better. While we work let's keep it commented out at the end of the preprocess_data function bc it kind of gets in the way of interpreting what's going on. We'll uncomment it at a later stage.

I agree, this order of operations makes much more sense. We are still wanting to remove the line spacing between paragraphs for each chapter though, right?

2023-10-07 23:37 UTC, andreicozma1 commented
> > I'm thinking there's possibly wrong order of operations in the preprocess.py function.
> > I think I've found a somewhat good order that is robust to that we can build upon that. It's still got some little quirks here and there (For example, Mr., Mrs., acronyms with periods, etc, but those are minor issues). However, the rest has got pretty good consistency. All paragraphs are separated by \n\n and sentences are separated by single \n
> > Let's work off this order for the fixes and improvements to add to this branch:
> > ![image](https://private-user-images.githubusercontent.com/14914491/273353546-c7334ac9-301a-41b5-b186-126ba5278e79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTY3MDkwOTYsIm5iZiI6MTY5NjcwODc5NiwicGF0aCI6Ii8xNDkxNDQ5MS8yNzMzNTM1NDYtYzczMzRhYzktMzAxYS00MWI1LWIxODYtMTI2YmE1Mjc4ZTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMDA3VDE5NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwM2Y1NTg1OGNmOTkyZWQ3MzQ3NDZiMjYxY2NlODQ2MGNmYjRjMmQ3ZDhmYmU2NjUyZDAwMmE2NmIxNzU2NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bvb4L4RB3JuOB-VvG_-9qBPqxqPqsFxHuudsUbKNm7o)
> > Result:
> > ![image](https://private-user-images.githubusercontent.com/14914491/273353612-56dd8ec2-74a2-49bd-87f0-bd86ad8cb563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTY3MDkwOTYsIm5iZiI6MTY5NjcwODc5NiwicGF0aCI6Ii8xNDkxNDQ5MS8yNzMzNTM2MTItNTZkZDhlYzItNzRhMi00OWJkLTg3ZjAtYmQ4NmFkOGNiNTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMDA3VDE5NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZDliNDZkMTIzMTY5ZWZmYWRmMGZiMmM5YTczNmVjYzU1NmM4YmI5ZDk1MjU4NmIzN2E5NjYwYjZhNTZhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-RdXDGrOQNvkySRZViaCj-A6dBZcxn2_oXdvWSKjyh0)
> > I removed the stopword removal in the above example to visualize it better. While we work let's keep it commented out at the end of the preprocess_data function bc it kind of gets in the way of interpreting what's going on. We'll uncomment it at a later stage.
> 
> I agree, this order of operations makes much more sense. We are still wanting to remove the line spacing between paragraphs for each chapter though, right?

Yeah for sure. Though we may not necessarily have to do that part using regex. It may also not necessarily need to be part of the preprocessing stage either.

We'll see when we get there, but we may need to do the chapter splitting before removing the line spacing between paragraphs. This way we still have double newlines between stuff including the chapter titles, which can help a lot in simplifying the chapter splitting part.

2023-10-07 23:45 UTC, andreicozma1 commented on lib/dataset.py
> +    return text
the line spacing between paragraphs sounds like something we should worry about later on, either in a separate regex or completely out of the preprocessing stage altogether.
The preprocessing stage should first try to resolve the bigger issues with the original text that makes it hard to process the way we need. For ex, misformatting, inconsistencies, etc should come first.
So step by step from the bigger things and eventually it allows us to funnel down to the details.

2023-10-07 23:46 UTC, andreicozma1 commented on lib/dataset.py
> +    chapter_map = create_chapter_map(text)
yeah that works, it helps to keep everything as separated as possible such that it's easier to make sure each stage works independently as intended

2023-10-08 19:42 UTC, zac-perry commented on lib/dataset.py
> +    formats = [r'^CHAPTER [IVXLCDM]+',  r'^Chapter [IVXLCDM]+',  r'^\d+']
Hey so I tried some new stuff in regards to getting the chapter headings for each book to use for the mapping. It's currently being done after the preprocessing (in my testing anyway) but there have been some issues. 

---

First, for the MBS and SOF books, I wrote this regex expression to extract the chapters and it does appear to work. It will get them regardless of casing (needs to have flag set in code). here is that expression: 
`\b(?:chapter|prologue)(?:\s+[ivxlcdm]+|\s+\d+)?\b(?=\n)`

<img width="1118" alt="image" src="https://github.com/Manan-dev/ChatRegex/assets/97002490/1263c347-e5ad-4875-a5ec-5093a1754d00">

--- 

Now for the Murder on the Links book, there have been a ton of issues. I was originally able to successfully extract them, but only before the preprocessing was done on the text. I have now been trying to find a way to do it after the preprocessing. Currently, this is the regex expression I have come up with: 
`(?<=\n{2})(\d+\s+[A-Za-z]+\s.+)(?=\n{2})`

This actually works, but also extracts 2 extra lines from the text that are not chapter headings. They have the same format though, so I'm not really sure of an intuitive way to differentiate them (You could brute force it for sure but it wouldn't be pretty). 

![image](https://github.com/Manan-dev/ChatRegex/assets/97002490/a9754a27-6e2e-4f22-b51a-6f6f143869d1)

- The yellow underlines are the 2 lines of text that are extracted as well.

---

This is what I have come up with for now. I was curious if you had any additional thoughts or ideas? My initial plan was, once both expression worked, to combine them so no matter the text, only one expression needs to be used. I also thought, it might be worth it to add in some more formatting stuff in the preprocessing step. More specifically, separating the chapter headings by an additional newline or something like that. Would probably make the extraction of the headings after the preprocessing a little easier.

Let me know what you think!

2023-10-08 20:55 UTC, zac-perry commented on lib/dataset.py
> +    formats = [r'^CHAPTER [IVXLCDM]+',  r'^Chapter [IVXLCDM]+',  r'^\d+']
I have realize there is a mistake with SOF extraction, as it is exacting from the table of contents and not the actual chapter heading. Will update that

2023-10-09 15:44 UTC, andreicozma1 commented on lib/dataset.py
> +    formats = [r'^CHAPTER [IVXLCDM]+',  r'^Chapter [IVXLCDM]+',  r'^\d+']
that looks really good! Regarding the Murder on the Links book, maybe we can check whether the book has a TOC section, then for each element in the TOC we could look where that's at in the rest of the text and insert the word "Chapter" to that line (only if it doesn't have it already), or a special token.
 
Some pseudocode:
```
# the below is going to be extracted from the TOC automatically
toc_elems = ["1 A Fellow Traveller", "2 An Appeal for Help", ........]

for elem in toc_elems:
    # The usage of ^ and $ might be pretty important here so we don't match in the middle of text
    matches = re. findall(f"^{elem}$", text)
    # Probably bad if we have more than 2 matches
    if len(matches) > 2:
        print(f"WARN: Expected 2 matches but got {len(matches)}")
        continue
    # Then add special token to the beginning of it

# Split like normal using re.split
```

it's technically still non-destructive which is nice, since we're only adding context but not changing anything

2023-10-11 14:25 UTC, closed without merging